(()=>{const NS=window.NS,C=NS.OBJECTIVE_FIELD,D=14,world=document.getElementById('world'),svg=document.getElementById('world-svg'),m=NS.buildObjectiveField({world,svg,includeHeroes:true,includeConstraints:false}),M=C.mutation,heroKey=M.affectedHero,hero=m.heroes.get(heroKey),engine=document.getElementById('engine-id');
 const inputLayer=document.createElement('div');inputLayer.className='ns-layer';inputLayer.style.zIndex='18';world.appendChild(inputLayer);const strategyLayer=document.createElement('div');strategyLayer.className='ns-layer';strategyLayer.style.zIndex='20';world.appendChild(strategyLayer);
 const inputs=C.inputs.map(s=>({spec:s,card:NS.inputCard(inputLayer,s)}));const chips=[];const xs={flight:4365,transfer1:4705,hotel:5045,transfer2:5385,objective:5725};C.inputs.forEach((s,i)=>{const st=s.structured,card=NS.constraint(inputLayer,{id:`structured-${s.id}`,x:st.x,y:st.y,label:st.label,value:st.value,tone:'green'}),tx=xs[st.target],ty=1572,sx=st.x+135,sy=st.y+(st.y<1450?84:0),path=NS.svgPath(svg,`structured-edge-${i}`,`M${sx} ${sy} C${sx} ${NS.lerp(sy,ty,.42)}, ${tx} ${NS.lerp(sy,ty,.72)}, ${tx} ${ty}`,'ns-edge is-ink');chips.push({spec:s,card,path})});
 const strategies=C.strategies.map(s=>({spec:s,card:NS.strategy(strategyLayer,s)}));const hub=document.createElement('div');hub.className='strategy-hub';Object.assign(hub.style,{left:'5280px',top:'1585px'});strategyLayer.appendChild(hub);const badge=document.createElement('div');badge.className='viability-badge';badge.textContent='DETERMINISTIC VIABILITY';Object.assign(badge.style,{left:'5195px',top:'1530px'});strategyLayer.appendChild(badge);
 const branches=strategies.map((s,i)=>{const ex=s.spec.x,ey=s.spec.y+88,d=`M5290 1594 C${NS.lerp(5290,ex,.42)} 1594, ${NS.lerp(5290,ex,.72)} ${ey}, ${ex} ${ey}`;return NS.svgPath(svg,`strategy-branch-${i}`,d,'ns-edge is-ink')});
 function applyImpact(){m.layers.health.style.opacity='.10';m.layers.mini.style.opacity='.14';[...m.dayLabels.values()].forEach(e=>e.style.opacity='.18');[...m.commitments.entries()].forEach(([id,e])=>e.style.opacity=id===M.commitment?'.82':'.12');m.programmeEdges.forEach(e=>e.style.opacity='.08');m.miniEdges.forEach(e=>e.path.style.opacity='.09');m.dockEdges.forEach(e=>e.path.style.opacity='.08');m.heroes.forEach((h,id)=>{h.root.style.opacity=id===heroKey?'1':'.08';h.targetEdge.style.opacity=id===heroKey?'.75':'.06'});['flight','transfer1','hotel','transfer2','objective'].forEach(id=>NS.setHeroStage(hero,id,M.stageStates[id],M.stageMeta[id]));NS.setTone(m.commitments.get(M.commitment),'brass')}
 applyImpact();
 function renderAt(t){t=NS.clamp(t,0,D);let p=NS.cubic(NS.window01(t,1.2,5.3));NS.setCamera(world,NS.lerp(C.cameras.affected37.x,C.cameras.strategy37.x,p),NS.lerp(C.cameras.affected37.y,C.cameras.strategy37.y,p),NS.lerp(C.cameras.affected37.scale,C.cameras.strategy37.scale,p));
  inputs.forEach((o,i)=>{const a=.75+i*.33,enter=NS.outCubic(NS.window01(t,a,a+.55)),leave=NS.smooth(NS.window01(t,3.45+i*.38,4.25+i*.38));o.card.style.opacity=String(enter*(1-leave));o.card.style.transform=`translateX(${NS.lerp(-18,0,enter)}px) scale(${NS.lerp(1,.94,leave)})`});
  chips.forEach((o,i)=>{const a=3.25+i*.42,q=NS.outCubic(NS.window01(t,a,a+.68));o.card.style.opacity=String(q);o.card.style.transform=`translateY(${NS.lerp(14,0,q)}px)`;o.path.style.opacity=String(q);NS.drawProgress(o.path,q)});
  // Strategies grow from the impacted trip, not from an external pipeline.
  const hubIn=NS.outCubic(NS.window01(t,6.55,7.05));hub.style.opacity=String(hubIn);badge.style.opacity=String(hubIn);branches.forEach((b,i)=>{const q=NS.smooth(NS.window01(t,6.85+i*.18,7.65+i*.18));b.style.opacity=String(q);NS.drawProgress(b,q);const c=strategies[i].card;c.style.opacity=String(NS.outCubic(NS.window01(t,7.25+i*.22,8.05+i*.22)));c.style.transform=`translateY(${NS.lerp(16,0,NS.outCubic(NS.window01(t,7.25+i*.22,8.05+i*.22)))}px)`});
  // Deterministic viability rejects branches that do not restore the objective.
  strategies.forEach((o,i)=>{if(o.spec.state!=='alert')return;const q=NS.smooth(NS.window01(t,9.75+i*.22,10.8+i*.22));o.card.style.opacity=String(NS.lerp(1,.16,q));o.card.style.transform=`scale(${NS.lerp(1,.92,q)})`;branches[i].style.opacity=String(NS.lerp(1,.14,q))});
  strategies.filter(o=>o.spec.state!=='alert').forEach((o,j)=>{const q=NS.bell(NS.window01(t,10.55+j*.3,11.7+j*.3));o.card.style.boxShadow=`0 18px 44px rgba(20,23,28,.06),0 0 0 ${4*q}px rgba(76,154,110,.12)`});
  const ei=NS.outCubic(NS.window01(t,11.3,12.35));engine.style.opacity=String(ei);
  if(t<=.001){NS.setCamera(world,C.cameras.affected37.x,C.cameras.affected37.y,C.cameras.affected37.scale);inputs.forEach(o=>o.card.style.opacity='0');chips.forEach(o=>{o.card.style.opacity='0';o.path.style.opacity='0'});strategies.forEach(o=>o.card.style.opacity='0');branches.forEach(b=>b.style.opacity='0');hub.style.opacity='0';badge.style.opacity='0';engine.style.opacity='0'}
 }
 NS.bootSequence({duration:D,renderAt});})();
