/**
 * RV-N6 — Atlas REPLAY evidence (Northstar Wave 2).
 *
 * Proves, on the real AtlasFlightAdapter:
 *  - REPLAY search/verify/fareRules resolve the test-local sanitized
 *    recordings deterministically and faithfully;
 *  - RECORD mode persists sanitized recordings (no credential material);
 *  - REPLAY and RECORD run the same normalizer — a recorded LIVE-shaped
 *    payload normalizes to the IDENTICAL CapabilityResult as REPLAY;
 *  - LIVE without credentials returns a structured NOT_CONFIGURED result,
 *    never crashes.
 *
 * Test-local recordings live under test/fixtures/recordings/ and are
 * generated by scripts/build-northstar-atlas-fixtures.ts. They use synthetic
 * identifiers, synthetic airport names and synthetic offer ids — never
 * real hotel/airline/city content.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  FileRecordingStore,
  containsAnySecret,
  recordingIdFor,
} from '../src/providers/index.ts';
import { AtlasFlightAdapter } from '../src/providers/atlas/adapter.ts';
import { atlasScheduleToIso } from '../src/providers/atlas/normalize.ts';
import type {
  FlightSearchOutcome,
  FlightSearchQuery,
  FlightVerifyOutcome,
  FareRulesOutcome,
} from '../src/contracts/capabilities.ts';

const TEST_FIXTURES = 'test/fixtures/recordings';
const MANILA = 'Asia/Manila';
const OFFER_ID = 'opaque-routing-identifier-001';

const SEARCH_QUERY: FlightSearchQuery = {
  origin: { system: 'IATA', value: 'MNL' },
  destination: { system: 'IATA', value: 'CEB' },
  departureDate: '2026-09-05',
  passengers: { adults: 1 },
};

const TIMEZONE_RESOLVER = (code: string): string | undefined =>
  code === 'MNL' || code === 'CEB' ? MANILA : undefined;

function replayStore(): FileRecordingStore {
  return new FileRecordingStore({ readDirs: [TEST_FIXTURES] });
}

function replayAdapter(): AtlasFlightAdapter {
  return new AtlasFlightAdapter({
    mode: 'REPLAY',
    store: replayStore(),
    timezoneResolver: TIMEZONE_RESOLVER,
  });
}

test('RV-N6 atlas: REPLAY search returns the recorded offer deterministically', async () => {
  const result = await replayAdapter().searchFlights(SEARCH_QUERY);
  assert.equal(result.ok, true, JSON.stringify(result.ok ? undefined : result.error));
  if (!result.ok) return;
  assert.equal(result.meta.mode, 'REPLAY');
  assert.equal(result.meta.recordingId, recordingIdFor('atlas', 'search', SEARCH_QUERY));
  assert.equal(result.data.offers.length, 1);

  const offer = result.data.offers[0]!;
  assert.equal(offer.offerId, OFFER_ID);
  assert.equal(offer.totalPrice.currency, 'USD');
  assert.equal(offer.totalPrice.amount, 120);
  assert.equal(offer.segments.length, 1);
  assert.equal(offer.segments[0]!.origin.value, 'MNL');
  assert.equal(offer.segments[0]!.destination.value, 'CEB');
  assert.equal(offer.segments[0]!.departure, atlasScheduleToIso('202609052000', MANILA));
  assert.equal(offer.segments[0]!.arrival, atlasScheduleToIso('202609052130', MANILA));
  assert.equal(offer.expiresAt, '2026-08-24T00:00:00Z');
});

test('RV-N6 atlas: REPLAY verify replays the recorded verify session verbatim', async () => {
  const result = await replayAdapter().verifyOffer({ offerId: OFFER_ID });
  assert.equal(result.ok, true, JSON.stringify(result.ok ? undefined : result.error));
  if (!result.ok) return;
  const outcome: FlightVerifyOutcome = result.data;
  assert.equal(outcome.status, 'VERIFIED');
  assert.deepEqual(outcome.workflowState, { sessionId: 'synthetic-session-id' });
  assert.deepEqual(outcome.bookingRequirements, [
    'passenger.birthday',
    'passenger.name',
    'passenger.nationality',
  ]);
  assert.equal(result.meta.recordingId, recordingIdFor('atlas', 'verify', { offerId: OFFER_ID }));
});

test('RV-N6 atlas: REPLAY getFareRules normalizes the rule block', async () => {
  const result = await replayAdapter().getFareRules({ offerId: OFFER_ID });
  assert.equal(result.ok, true, JSON.stringify(result.ok ? undefined : result.error));
  if (!result.ok) return;
  const rules: FareRulesOutcome = result.data;
  assert.equal(rules.change?.allowed, true);
  assert.equal(rules.refund?.refundable, true);
  assert.ok(rules.noShow?.consequence.length);
  assert.equal(rules.baggageIncluded?.length, 1);
  assert.equal(result.meta.recordingId, recordingIdFor('atlas', 'fare_rules', { offerId: OFFER_ID }));
});

test('RV-N6 atlas: RECORD writes sanitized recordings (no credential material)', async () => {
  const injectedSecret = 'injected-credential-do-not-persist';
  const liveRaw = {
    status: 0,
    msg: `probe ${injectedSecret}`,
    routings: [
      {
        routingIdentifier: OFFER_ID,
        currency: 'USD',
        adultPrice: 100,
        adultTax: 20,
        fromSegments: [
          {
            depAirport: 'MNL',
            arrAirport: 'CEB',
            depTime: '202609052000',
            arrTime: '202609052130',
            seatCount: 9,
          },
        ],
        retSegments: [],
        riskSellout: false,
        rule: {
          changesRules: [{ changesStatus: 'T' }],
          refundRules: [{ refundStatus: 'T' }],
        },
      },
    ],
  };

  const writeDir = mkdtempSync(join(tmpdir(), 'rv-n6-atlas-'));
  const store = new FileRecordingStore({ readDirs: [writeDir], writeDir });
  const stubFetch: typeof fetch = async () =>
    new Response(JSON.stringify(liveRaw), { status: 200 });

  const adapter = new AtlasFlightAdapter({
    mode: 'RECORD',
    store,
    baseUrl: 'https://sandbox.example',
    clientId: 'client-id-should-be-removed',
    clientSecret: injectedSecret,
    fetchImpl: stubFetch,
    timezoneResolver: TIMEZONE_RESOLVER,
  });

  const result = await adapter.searchFlights(SEARCH_QUERY);
  assert.equal(result.ok, true);
  if (!result.ok) return;
  const recordingPath = join(writeDir, 'atlas', 'search', `${result.meta.recordingId}.json`);
  assert.ok(existsSync(recordingPath), 'recording must be persisted under writeDir');
  const persisted = JSON.parse(readFileSync(recordingPath, 'utf8')) as { raw: unknown; sanitized: boolean };
  assert.equal(persisted.sanitized, true);
  // Credentials MUST NOT appear anywhere in the persisted body.
  assert.equal(containsAnySecret(persisted.raw, [injectedSecret, 'client-id-should-be-removed']), false);
  const serialized = JSON.stringify(persisted.raw);
  assert.ok(!serialized.includes(injectedSecret), 'secret leak check');
  assert.ok(!serialized.includes('client-id-should-be-removed'), 'client id leak check');
});

test('RV-N6 atlas: REPLAY and RECORD normalize identical LIVE-shaped payloads to identical outcomes', async () => {
  // Author a fresh LIVE-shaped payload distinct from the curated fixtures so
  // the recording is written into a clean temp dir.
  const liveRaw = {
    status: 0,
    msg: null,
    routings: [
      {
        routingIdentifier: 'live-shaped-identifier-001',
        currency: 'USD',
        adultPrice: 50,
        adultTax: 5,
        childPrice: 40,
        childTax: 4,
        infantPrice: 0,
        infantTax: 0,
        expireTime: null,
        refreshTime: null,
        fromSegments: [
          {
            carrier: 'YY',
            flightNumber: 'YY007',
            depAirport: 'MNL',
            arrAirport: 'CEB',
            depTime: '202609052200',
            arrTime: '202609052330',
            duration: 90,
            cabin: '',
            cabinClass: 1,
            fareFamily: 'Flexible',
            seatCount: 4,
            segmentIndex: 1,
          },
        ],
        retSegments: [],
        riskSellout: true,
        rule: {
          changesRules: [{ changesStatus: 'F', currency: 'USD' }],
          refundRules: [{ refundStatus: 'F', currency: 'USD' }],
        },
      },
    ],
  };

  const writeDir = mkdtempSync(join(tmpdir(), 'rv-n6-atlas-equiv-'));
  const store = new FileRecordingStore({ readDirs: [writeDir], writeDir });
  const stubFetch: typeof fetch = async () =>
    new Response(JSON.stringify(liveRaw), { status: 200 });

  const recordAdapter = new AtlasFlightAdapter({
    mode: 'RECORD',
    store,
    baseUrl: 'https://sandbox.example',
    clientId: 'cid',
    clientSecret: 'csecret',
    fetchImpl: stubFetch,
    timezoneResolver: TIMEZONE_RESOLVER,
  });
  const liveQuery: FlightSearchQuery = { ...SEARCH_QUERY, departureDate: '2026-09-06' };
  const liveSide = await recordAdapter.searchFlights(liveQuery);
  assert.equal(liveSide.ok, true);
  if (!liveSide.ok) return;

  const replaySide = await new AtlasFlightAdapter({
    mode: 'REPLAY',
    store,
    timezoneResolver: TIMEZONE_RESOLVER,
  }).searchFlights(liveQuery);
  assert.equal(replaySide.ok, true);
  if (!replaySide.ok) return;

  assert.deepEqual(
    replaySide.data as FlightSearchOutcome,
    liveSide.data as FlightSearchOutcome,
    'the shared normalizer must yield byte-identical outcomes for the same raw payload',
  );
  assert.equal(replaySide.meta.recordingId, liveSide.meta.recordingId);
  assert.equal(replaySide.meta.mode, 'REPLAY');
  assert.equal(liveSide.meta.mode, 'RECORD');
});

test('RV-N6 atlas: LIVE without credentials fails structured, never crashes', async () => {
  const adapter = new AtlasFlightAdapter({ mode: 'LIVE', store: replayStore() });
  const result = await adapter.searchFlights(SEARCH_QUERY);
  assert.equal(result.ok, false);
  if (result.ok) return;
  assert.equal(result.error.category, 'NOT_CONFIGURED');
  assert.equal(result.error.code, 'atlas_missing_credentials');
  assert.match(result.error.message, /ATLAS_(BASE_URL|CLIENT_ID|CLIENT_SECRET)/);
  assert.equal(result.meta.mode, 'LIVE');
});

test('RV-N6 atlas: REPLAY surface is a real CapabilityResult envelope with meta', async () => {
  const result = await replayAdapter().searchFlights(SEARCH_QUERY);
  assert.equal(result.ok, true);
  if (!result.ok) return;
  // Every REPLAY call surfaces a recordingId and providerId on the meta.
  assert.equal(result.meta.providerId, 'atlas');
  assert.equal(result.meta.mode, 'REPLAY');
  assert.ok(result.meta.recordingId?.startsWith('rec_'));
  assert.ok(typeof result.meta.requestedAt === 'string');
});
