/**
 * R2 — Case polling script tests.
 *
 * Verifies the inline <script> generated by casePollingScript() contains the
 * required contract elements: endpoint, sinceCursor echo, interval, no WebSockets,
 * complete-snapshot swap, terminal + hidden-document pause guards, and deterministic
 * output.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { casePollingScript } from '../src/ui/casePolling.ts';

test('casePollingScript contains the case endpoint with format=html', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('/api/v2/cases/'), 'must contain case endpoint');
  assert.ok(script.includes('format=html'), 'must request HTML format');
  assert.ok(script.includes('CASE-001'), 'must include the caseRef');
});

test('casePollingScript carries sinceCursor echo logic', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('sinceCursor'), 'must reference sinceCursor');
  assert.ok(script.includes('lastAppliedCursor'), 'must track last applied cursor');
  assert.ok(script.includes('encodeURIComponent(lastAppliedCursor)'), 'must encode cursor in URL');
});

test('casePollingScript has default interval 4000ms', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('setInterval(refresh, 4000)'), 'default interval must be 4000ms');
});

test('casePollingScript interval is configurable', () => {
  const script = casePollingScript({ caseRef: 'CASE-001', intervalMs: 5000 });
  assert.ok(script.includes('setInterval(refresh, 5000)'), 'custom interval must be applied');
  assert.ok(!script.includes('setInterval(refresh, 4000)'), 'default must not appear when custom is set');
});

test('casePollingScript contains no WebSocket or EventSource tokens', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(!script.includes('WebSocket'), 'must not use WebSocket');
  assert.ok(!script.includes('EventSource'), 'must not use SSE');
  assert.ok(!script.includes('ws://'), 'must not reference ws://');
  assert.ok(!script.includes('wss://'), 'must not reference wss://');
});

test('casePollingScript contains complete-snapshot swap selector', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('main[data-test="product-recovery-case"]'), 'must target case main region');
  assert.ok(script.includes('outerHTML'), 'must swap entire main region (complete snapshot)');
});

test('casePollingScript contains terminal status pause guard', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('TERMINAL_STATUSES'), 'must define terminal statuses');
  assert.ok(script.includes('RESOLVED'), 'must include RESOLVED');
  assert.ok(script.includes('CLOSED'), 'must include CLOSED');
  assert.ok(script.includes('CANCELLED'), 'must include CANCELLED');
  assert.ok(script.includes('SUPERSEDED'), 'must include SUPERSEDED');
  assert.ok(script.includes('isTerminal'), 'must check terminal status');
  assert.ok(script.includes('data-case-status'), 'must read status from data attribute');
});

test('casePollingScript contains hidden-document pause guard', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('document.hidden'), 'must check document.hidden');
  assert.ok(script.includes('visibilitychange'), 'must listen to visibilitychange');
});

test('casePollingScript preserves user-opened details state', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('details[open]'), 'must query open details');
  assert.ok(script.includes('setAttribute(\'open\', \'\')'), 'must restore open state');
});

test('casePollingScript output is deterministic', () => {
  const script1 = casePollingScript({ caseRef: 'CASE-001', intervalMs: 4000 });
  const script2 = casePollingScript({ caseRef: 'CASE-001', intervalMs: 4000 });
  assert.equal(script1, script2, 'same options must produce identical output');
});

test('casePollingScript output differs for different caseRef', () => {
  const script1 = casePollingScript({ caseRef: 'CASE-001' });
  const script2 = casePollingScript({ caseRef: 'CASE-002' });
  assert.notEqual(script1, script2, 'different caseRef must produce different output');
});

test('casePollingScript output differs for different intervalMs', () => {
  const script1 = casePollingScript({ caseRef: 'CASE-001', intervalMs: 4000 });
  const script2 = casePollingScript({ caseRef: 'CASE-001', intervalMs: 5000 });
  assert.notEqual(script1, script2, 'different intervalMs must produce different output');
});

test('casePollingScript contains no-op redraw guard', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('lastAppliedRevision'), 'must track last applied revision');
  assert.ok(script.includes('newCursor === lastAppliedCursor'), 'must compare cursors');
  assert.ok(script.includes('newRevision === lastAppliedRevision'), 'must compare revisions');
});

test('casePollingScript exposes refresh function for external triggers', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('__northstarRefreshCase'), 'must expose refresh function');
});

test('casePollingScript guards against double-init', () => {
  const script = casePollingScript({ caseRef: 'CASE-001' });
  assert.ok(script.includes('__northstarCasePollStarted'), 'must guard against double-init');
});
