(()=>{const NS=window.NS,C=NS.OBJECTIVE_FIELD,D=9,world=document.getElementById('world'),svg=document.getElementById('world-svg'),m=NS.buildObjectiveField({world,svg,includeHeroes:true,includeConstraints:false}),M=C.mutation,heroKey=M.affectedHero,hero=m.heroes.get(heroKey),key=document.getElementById('role-key');
 const layer=document.createElement('div');layer.className='ns-layer';layer.style.zIndex='22';world.appendChild(layer);
 const chips=C.inputs.map((s,i)=>{const st=s.structured,card=NS.constraint(layer,{id:`structured-${s.id}`,x:st.x,y:st.y,label:st.label,value:st.value,tone:'green'});return{spec:s,card}});
 const survivors=C.strategies.filter(s=>C.recovery.viableStrategyIds.includes(s.id)).map(s=>({spec:s,card:NS.strategy(layer,s)}));const qwen=NS.service(layer,C.integrations.qwen),atlas=NS.service(layer,C.integrations.atlas),evidence=NS.evidence(layer,C.integrations.evidence);
 const qwenEdges=chips.slice(0,4).map((c,i)=>NS.svgPath(svg,`qwen-in-${i}`,`M${c.spec.structured.x+135} ${c.spec.structured.y+42} C3500 ${c.spec.structured.y+42}, 3660 610, 3780 610`,'ns-edge is-ink'));
 const qwenOut=survivors.map((o,i)=>NS.svgPath(svg,`qwen-out-${i}`,`M3970 608 C4550 ${620+i*120}, ${o.spec.x-420} ${o.spec.y+70}, ${o.spec.x} ${o.spec.y+70}`,'ns-edge is-ink'));
 const combined=survivors.find(o=>o.spec.id===C.recovery.atlasStrategyId),atlasReq=NS.svgPath(svg,'atlas-request',`M${combined.spec.x+350} ${combined.spec.y+88} C6260 ${combined.spec.y+80}, 6220 1770, 6250 1770`,'ns-edge is-ink'),atlasReturn=NS.svgPath(svg,'atlas-return',`M6380 1940 C6200 2040, 6000 2010, ${combined.spec.x+250} ${combined.spec.y+150}`,'ns-edge is-green');
 const search=document.createElement('div');search.className='service-step';search.textContent='SEARCH';Object.assign(search.style,{left:'6310px',top:'1810px'});layer.appendChild(search);const verify=document.createElement('div');verify.className='service-step';verify.innerHTML='VERIFY <strong>✓</strong>';Object.assign(verify.style,{left:'6440px',top:'1810px'});layer.appendChild(verify);
 function impacted(){m.layers.health.style.opacity='.08';m.layers.mini.style.opacity='.10';[...m.dayLabels.values()].forEach(e=>e.style.opacity='.12');[...m.commitments.entries()].forEach(([id,e])=>e.style.opacity=id===M.commitment?'.70':'.08');m.programmeEdges.forEach(e=>e.style.opacity='.06');m.miniEdges.forEach(e=>e.path.style.opacity='.05');m.dockEdges.forEach(e=>e.path.style.opacity='.05');m.heroes.forEach((h,id)=>{h.root.style.opacity=id===heroKey?'.72':'.05';h.targetEdge.style.opacity=id===heroKey?'.56':'.04'});['flight','transfer1','hotel','transfer2','objective'].forEach(id=>NS.setHeroStage(hero,id,M.stageStates[id],M.stageMeta[id]));NS.setTone(m.commitments.get(M.commitment),'brass')}
 function renderAt(t){t=NS.clamp(t,0,D);impacted();const cam=NS.cubic(NS.window01(t,.4,2.0));NS.setCamera(world,NS.lerp(C.cameras.strategy37.x,C.cameras.integration.x,cam),NS.lerp(C.cameras.strategy37.y,C.cameras.integration.y,cam),NS.lerp(C.cameras.strategy37.scale,C.cameras.integration.scale,cam));chips.forEach(c=>c.card.style.opacity='.82');survivors.forEach(o=>o.card.style.opacity='1');
  const qi=NS.outCubic(NS.window01(t,.9,1.65));qwen.style.opacity=String(qi);qwen.style.transform=`translateY(${NS.lerp(-15,0,qi)}px)`;qwenEdges.forEach((e,i)=>{const p=NS.smooth(NS.window01(t,1.25+i*.12,2.15+i*.12));e.style.opacity=String(p*.72);NS.drawProgress(e,p)});qwenOut.forEach((e,i)=>{const p=NS.smooth(NS.window01(t,2.25+i*.18,3.15+i*.18));e.style.opacity=String(p*.72);NS.drawProgress(e,p)});
  const ai=NS.outCubic(NS.window01(t,3.75,4.55));atlas.style.opacity=String(ai);atlas.style.transform=`translateY(${NS.lerp(16,0,ai)}px)`;const req=NS.smooth(NS.window01(t,4.4,5.4));atlasReq.style.opacity=String(req);NS.drawProgress(atlasReq,req);search.style.opacity=String(NS.outCubic(NS.window01(t,4.9,5.35)));verify.style.opacity=String(NS.outCubic(NS.window01(t,5.35,5.95)));
  const ev=NS.outCubic(NS.window01(t,5.65,6.45));evidence.style.opacity=String(ev);evidence.style.transform=`translateY(${NS.lerp(14,0,ev)}px)`;const ret=NS.smooth(NS.window01(t,6.25,7.15));atlasReturn.style.opacity=String(ret);NS.drawProgress(atlasReturn,ret);if(ret>.55){combined.card.classList.remove('is-active');combined.card.classList.add('is-ok');combined.card.querySelector('.result').textContent='✓ VIABLE · FLIGHT VERIFIED'}else{combined.card.classList.remove('is-ok');combined.card.classList.add('is-active');combined.card.querySelector('.result').textContent='✓ VIABLE · VERIFY FLIGHT'}
  const k=NS.outCubic(NS.window01(t,7.0,7.65));key.style.opacity=String(k);
  if(t<=.001){NS.setCamera(world,C.cameras.strategy37.x,C.cameras.strategy37.y,C.cameras.strategy37.scale);qwen.style.opacity='0';atlas.style.opacity='0';evidence.style.opacity='0';qwenEdges.forEach(e=>e.style.opacity='0');qwenOut.forEach(e=>e.style.opacity='0');atlasReq.style.opacity='0';atlasReturn.style.opacity='0';search.style.opacity='0';verify.style.opacity='0';key.style.opacity='0'}
 }
 NS.bootSequence({duration:D,renderAt});})();
