(()=>{const NS=window.NS,C=NS.OBJECTIVE_FIELD,D=9,world=document.getElementById('world'),svg=document.getElementById('world-svg'),m=NS.buildObjectiveField({world,svg,includeHeroes:true,includeConstraints:false}),M=C.mutation,heroKey=M.affectedHero,hero=m.heroes.get(heroKey),key=document.getElementById('role-key');
 const layer=document.createElement('div');layer.className='ns-layer';layer.style.zIndex='22';world.appendChild(layer);
 const chips=C.inputs.map((s,i)=>{const st=s.structured,card=NS.constraint(layer,{id:`structured-${s.id}`,x:st.x,y:st.y,label:st.label,value:st.value,tone:'green'});return{spec:s,card}});
 const survivors=C.strategies.filter(s=>C.recovery.viableStrategyIds.includes(s.id)).map(s=>({spec:s,card:NS.strategy(layer,s)}));const Q=C.integrations.qwen,A=C.integrations.atlas,E=C.integrations.evidence,qwen=NS.service(layer,Q),atlas=NS.service(layer,A),evidence=NS.evidence(layer,E);
 const qwenEdges=chips.slice(0,4).map((c,i)=>NS.svgPath(svg,`qwen-in-${i}`,`M${c.spec.structured.x+135} ${c.spec.structured.y+42} C${Q.x-100} ${c.spec.structured.y+42}, ${Q.x+60} ${Q.y+180}, ${Q.x+180} ${Q.y+180}`,'ns-edge is-ink'));
 const qwenOut=survivors.map((o,i)=>NS.svgPath(svg,`qwen-out-${i}`,`M${Q.x+370} ${Q.y+178} C${Q.x+550} ${Q.y+190+i*120}, ${o.spec.x-420} ${o.spec.y+70}, ${o.spec.x} ${o.spec.y+70}`,'ns-edge is-ink'));
 const combined=survivors.find(o=>o.spec.id===C.recovery.atlasStrategyId),atlasReq=NS.svgPath(svg,'atlas-request',`M${combined.spec.x+350} ${combined.spec.y+88} C${A.x-80} ${combined.spec.y+80}, ${A.x-30} ${A.y+90}, ${A.x} ${A.y+90}`,'ns-edge is-ink'),atlasReturn=NS.svgPath(svg,'atlas-return',`M${E.x+180} ${E.y} C${E.x} ${E.y+100}, ${A.x-250} ${E.y+70}, ${combined.spec.x+250} ${combined.spec.y+150}`,'ns-edge is-green');
 let verifiedState;
 function setVerification(verified){if(verifiedState===verified)return;verifiedState=verified;combined.card.classList.toggle('is-active',!verified);combined.card.classList.toggle('is-ok',verified);combined.card.querySelector('.result').textContent=verified?'✓ VIABLE · FLIGHT VERIFIED':'✓ VIABLE · VERIFY FLIGHT'}
 const search=document.createElement('div');search.className='service-step';search.textContent='SEARCH';Object.assign(search.style,{left:(A.x+60)+'px',top:(A.y+130)+'px'});layer.appendChild(search);const verify=document.createElement('div');verify.className='service-step';verify.innerHTML='VERIFY <strong>✓</strong>';Object.assign(verify.style,{left:(A.x+190)+'px',top:(A.y+130)+'px'});layer.appendChild(verify);
 function impacted(){m.layers.health.style.opacity='.08';m.layers.mini.style.opacity='.10';[...m.dayLabels.values()].forEach(e=>e.style.opacity='.12');[...m.commitments.entries()].forEach(([id,e])=>e.style.opacity=id===M.commitment?'.70':'.08');m.programmeEdges.forEach(e=>e.style.opacity='.06');m.miniEdges.forEach(e=>e.path.style.opacity='.05');m.dockEdges.forEach(e=>e.path.style.opacity='.05');m.heroes.forEach((h,id)=>{h.root.style.opacity=id===heroKey?'.72':'.05';h.targetEdge.style.opacity=id===heroKey?'.56':'.04'});['flight','transfer1','hotel','transfer2','objective'].forEach(id=>NS.setHeroStage(hero,id,M.stageStates[id],M.stageMeta[id]));NS.setTone(m.commitments.get(M.commitment),'brass')}
 impacted();
 function renderAt(t){t=NS.clamp(t,0,D);const cam=NS.cubic(NS.window01(t,.4,2.0));NS.setCamera(world,NS.lerp(C.cameras.strategy37.x,C.cameras.integration.x,cam),NS.lerp(C.cameras.strategy37.y,C.cameras.integration.y,cam),NS.lerp(C.cameras.strategy37.scale,C.cameras.integration.scale,cam));chips.forEach(c=>c.card.style.opacity='.82');survivors.forEach(o=>o.card.style.opacity='1');
  const qi=NS.outCubic(NS.window01(t,.9,1.65));qwen.style.opacity=String(qi);qwen.style.transform=`translateY(${NS.lerp(-15,0,qi)}px)`;qwenEdges.forEach((e,i)=>{const p=NS.smooth(NS.window01(t,1.25+i*.12,2.15+i*.12));e.style.opacity=String(p*.72);NS.drawProgress(e,p)});qwenOut.forEach((e,i)=>{const p=NS.smooth(NS.window01(t,2.25+i*.18,3.15+i*.18));e.style.opacity=String(p*.72);NS.drawProgress(e,p)});
  const ai=NS.outCubic(NS.window01(t,3.75,4.55));atlas.style.opacity=String(ai);atlas.style.transform=`translateY(${NS.lerp(16,0,ai)}px)`;const req=NS.smooth(NS.window01(t,4.4,5.4));atlasReq.style.opacity=String(req);NS.drawProgress(atlasReq,req);search.style.opacity=String(NS.outCubic(NS.window01(t,4.9,5.35)));verify.style.opacity=String(NS.outCubic(NS.window01(t,5.35,5.95)));
  const ev=NS.outCubic(NS.window01(t,5.65,6.45));evidence.style.opacity=String(ev);evidence.style.transform=`translateY(${NS.lerp(14,0,ev)}px)`;const ret=NS.smooth(NS.window01(t,6.25,7.15));atlasReturn.style.opacity=String(ret);NS.drawProgress(atlasReturn,ret);setVerification(ret>.55)
  const k=NS.outCubic(NS.window01(t,7.0,7.65));key.style.opacity=String(k);
  if(t<=.001){NS.setCamera(world,C.cameras.strategy37.x,C.cameras.strategy37.y,C.cameras.strategy37.scale);qwen.style.opacity='0';atlas.style.opacity='0';evidence.style.opacity='0';qwenEdges.forEach(e=>e.style.opacity='0');qwenOut.forEach(e=>e.style.opacity='0');atlasReq.style.opacity='0';atlasReturn.style.opacity='0';search.style.opacity='0';verify.style.opacity='0';key.style.opacity='0'}
 }
 NS.bootSequence({duration:D,renderAt});})();
