(()=>{const NS=window.NS,C=NS.OBJECTIVE_FIELD,D=12,world=document.getElementById('world'),svg=document.getElementById('world-svg'),m=NS.buildObjectiveField({world,svg,includeHeroes:true,includeConstraints:false}),id=document.getElementById('authority-id');
 const layer=document.createElement('div');layer.className='ns-layer';layer.style.zIndex='24';world.appendChild(layer);const programme=NS.strategy(layer,C.strategies.find(s=>s.id===C.authority.human.strategyId)),combined=NS.strategy(layer,{...C.strategies.find(s=>s.id===C.authority.auto.strategyId),state:'ok',result:'✓ VIABLE · FLIGHT VERIFIED'}),qwen=NS.service(layer,C.integrations.qwen),atlas=NS.service(layer,C.integrations.atlas),evidence=NS.evidence(layer,C.integrations.evidence);
 const rule=document.createElement('div');rule.className='ns-authority-rule';Object.assign(rule.style,{left:C.authority.rule.x+'px',top:C.authority.rule.y+'px',width:C.authority.rule.w+'px'});layer.appendChild(rule);const title=document.createElement('div');title.className='threshold-title';title.textContent='AUTHORITY THRESHOLD';Object.assign(title.style,{left:C.authority.rule.x+'px',top:(C.authority.rule.y-34)+'px'});layer.appendChild(title);
 const auto=NS.action(layer,C.authority.auto),human=NS.action(layer,C.authority.human),decision=NS.decision(layer,C.authority.decision),autoPath=NS.svgPath(svg,'auto-path',`M${combined.offsetLeft+350} ${combined.offsetTop+88} C6100 2070, 5750 2210, ${C.authority.auto.x+100} ${C.authority.auto.y}`,'ns-edge is-green'),humanPath=NS.svgPath(svg,'human-path',`M${programme.offsetLeft+350} ${programme.offsetTop+88} C5700 2050, 6250 2160, ${C.authority.human.x+80} ${C.authority.human.y}`,'ns-edge is-red');
 const observed=document.createElement('div');observed.className='observed';observed.textContent='✓ OBSERVED · STATE UPDATED';Object.assign(observed.style,{left:'5650px',top:'2470px'});layer.appendChild(observed);
 function background(){m.layers.health.style.opacity='.05';m.layers.mini.style.opacity='.06';[...m.dayLabels.values(),...m.commitments.values()].forEach(e=>e.style.opacity='.06');m.programmeEdges.forEach(e=>e.style.opacity='.04');m.miniEdges.forEach(e=>e.path.style.opacity='.04');m.dockEdges.forEach(e=>e.path.style.opacity='.04');m.heroes.forEach(h=>{h.root.style.opacity='.14';h.targetEdge.style.opacity='.10'})}
 function renderAt(t){t=NS.clamp(t,0,D);background();let cam=NS.cubic(NS.window01(t,.35,2.2)),x=NS.lerp(C.cameras.integration.x,C.cameras.authority.x,cam),y=NS.lerp(C.cameras.integration.y,C.cameras.authority.y,cam),s=NS.lerp(C.cameras.integration.scale,C.cameras.authority.scale,cam);const push=NS.cubic(NS.window01(t,8.55,11.7));x=NS.lerp(x,C.seq10Handoff.camera.x,push);y=NS.lerp(y,C.seq10Handoff.camera.y,push);s=NS.lerp(s,C.seq10Handoff.camera.scale,push);NS.setCamera(world,x,y,s);
  programme.style.opacity=String(1-NS.smooth(NS.window01(t,9.0,10.0))*push*.7);combined.style.opacity=programme.style.opacity;qwen.style.opacity=String(NS.lerp(.78,.10,NS.smooth(NS.window01(t,.4,3.1))));atlas.style.opacity=qwen.style.opacity;evidence.style.opacity=qwen.style.opacity;
  const ri=NS.outCubic(NS.window01(t,1.25,2.05));rule.style.opacity=String(ri);rule.style.transform=`scaleX(${ri})`;title.style.opacity=String(ri);id.style.opacity=String(ri);
  const ap=NS.smooth(NS.window01(t,2.1,3.2));autoPath.style.opacity=String(ap);NS.drawProgress(autoPath,ap);auto.style.opacity=String(NS.outCubic(NS.window01(t,2.8,3.55)));auto.style.transform=`translateY(${NS.lerp(14,0,NS.outCubic(NS.window01(t,2.8,3.55)))}px)`;const settle=NS.bell(NS.window01(t,3.55,4.55));auto.style.boxShadow=`0 16px 40px rgba(20,23,28,.055),0 0 0 ${5*settle}px rgba(76,154,110,.12)`;observed.style.opacity=String(NS.outCubic(NS.window01(t,4.15,4.9)));
  const hp=NS.smooth(NS.window01(t,4.75,5.9));humanPath.style.opacity=String(hp);NS.drawProgress(humanPath,hp);human.style.opacity=String(NS.outCubic(NS.window01(t,5.45,6.15)));human.style.transform=`translateY(${NS.lerp(14,0,NS.outCubic(NS.window01(t,5.45,6.15)))}px)`;
  const di=NS.outCubic(NS.window01(t,6.55,7.45));decision.style.opacity=String(di);decision.style.transform=`translateY(${NS.lerp(22,0,di)}px) scale(${NS.lerp(.97,1,di)})`;if(push>.02){[rule,title,auto,human,observed,autoPath,humanPath,qwen,atlas,evidence].forEach(e=>e.style.opacity=String((Number(e.style.opacity)||0)*(1-push)));decision.style.opacity='1'}
  if(t<=.001){NS.setCamera(world,C.cameras.integration.x,C.cameras.integration.y,C.cameras.integration.scale);qwen.style.opacity='.78';atlas.style.opacity='.78';evidence.style.opacity='.78';programme.style.opacity='1';combined.style.opacity='1';[rule,title,auto,human,decision,observed,autoPath,humanPath].forEach(e=>e.style.opacity='0');id.style.opacity='0'}
 }
 NS.bootSequence({duration:D,renderAt});})();
