(()=>{const NS=window.NS,C=NS.OBJECTIVE_FIELD,D=6,world=document.getElementById('world'),svg=document.getElementById('world-svg');
 const m=NS.buildObjectiveField({world,svg,includeHeroes:false,includeConstraints:false}),carry=document.getElementById('carry-layer');
 // Seq05 opens on the accepted Seq04 far-state itself, not a visual approximation.
 // These are sequence-specific carryover objects and intentionally disappear as
 // the existing marks unfold into the new objective-field grammar.
 const carrySpec=C.seq04Carry,carryHealth=document.createElement('div');carryHealth.id='carry-health-layer';carry.appendChild(carryHealth);
 let carryId=1;for(let row=0;row<12;row++){for(let col=0;col<6;col++){if(carryId===17)carryId++;if(carryId>72)break;const P=NS.objectiveHealthPosition(carryId),out=C.scaleField.outcomes[carryId]||['green','✓'],e=document.createElement('div');e.className=`carry-health is-${out[0]}`;Object.assign(e.style,{left:P.x+'px',top:P.y+'px'});e.innerHTML='<i></i><i></i><i></i><i></i><span class="glyph">'+out[1]+'</span>';carryHealth.appendChild(e);carryId++}}
 const heroHeading=document.createElement('div');heroHeading.className='carry-heading';heroHeading.style.left=carrySpec.hero.headingX+'px';heroHeading.style.top=carrySpec.hero.headingY+'px';const [carryHeroTitle,...carryHeroRest]=carrySpec.hero.heading.split(' · ');heroHeading.innerHTML=`<strong>${carryHeroTitle}</strong> · ${carryHeroRest.join(' · ')}`;carry.appendChild(heroHeading);
 const legacyNodes=carrySpec.hero.nodes.map(s=>{const e=document.createElement('section');e.className=`carry-journey-node is-${s.tone}${s.wide?' is-wide':''}`;Object.assign(e.style,{left:s.x+'px',top:'820px'});e.innerHTML=`<div class="kicker">${s.kicker}</div><div class="value">${s.value}</div><div class="meta">${s.meta}</div><div class="state"></div>`;carry.appendChild(e);return e});
 const legacyEdges=carrySpec.hero.edges.map(s=>NS.svgPath(svg,`carry-hero-${s.id}`,s.d,`carry-hero-edge is-${s.tone}`));
 const supplier=document.createElement('section');supplier.id='supplier-card';supplier.innerHTML=`<div class="top"><span class="ns-label">SUPPLIER SIGNAL</span><span class="supplier-dot"></span></div><div class="title">${carrySpec.supplier.title}</div><div class="foot"><span>${carrySpec.supplier.affected}</span><span>${carrySpec.supplier.scope}</span></div>`;carry.appendChild(supplier);
 const supplierEdges=carrySpec.supplier.representative.map((id,i)=>{const P=NS.objectiveHealthPosition(id),d=`M1070 415 C${1420+(id%3)*150} ${430+(id%4)*55}, ${Math.max(1550,P.x-480)} ${P.y+18}, ${P.x} ${P.y+18}`;return NS.svgPath(svg,`carry-supplier-${id}`,d,'carry-supplier-edge')});
 const scaleHud=document.getElementById('scale-hud'),summary=document.getElementById('state-summary'),threshold=document.getElementById('threshold'),connected=document.getElementById('connected-id');
 const nId=document.getElementById('northstar-id'),mode=document.getElementById('stage-mode');
 const allProgramme=[...m.dayLabels.values(),...m.commitments.values(),...m.programmeEdges,...m.miniEdges.map(x=>x.path),...m.dockEdges.map(x=>x.path)];allProgramme.forEach(e=>e.style.opacity='0');m.layers.mini.style.opacity='0';
 function renderAt(t){t=NS.clamp(t,0,D);const cam=NS.cubic(NS.window01(t,.35,5.55));NS.setCamera(world,NS.lerp(C.cameras.seq04Final.x,C.cameras.programme.x,cam),NS.lerp(C.cameras.seq04Final.y,C.cameras.programme.y,cam),NS.lerp(C.cameras.seq04Final.scale,C.cameras.programme.scale,cam));
  const quiet=NS.smooth(NS.window01(t,.25,1.45));scaleHud.style.opacity=String(1-quiet);summary.style.opacity=String(1-quiet);threshold.style.opacity=String(1-quiet);supplier.style.opacity=String(1-quiet);supplierEdges.forEach(e=>e.style.opacity=String((1-quiet)*.82));nId.style.opacity=String(NS.lerp(1,.54,quiet));nId.textContent=t>3.7?'NORTHSTAR · CONNECTED STATE':'NORTHSTAR · TRIP STATE';mode.style.opacity=String(1-quiet);
  const carryMorph=NS.smooth(NS.window01(t,.30,1.28));carryHealth.style.opacity=String(1-carryMorph);legacyNodes.forEach(e=>e.style.opacity=String(1-carryMorph));legacyEdges.forEach(e=>e.style.opacity=String(1-carryMorph));heroHeading.style.opacity=String((1-carryMorph)*.28);
  const farQuiet=NS.lerp(1,.58,NS.smooth(NS.window01(t,.7,4.8)));m.layers.health.style.opacity=String(carryMorph*farQuiet);
  // Relationship-led discovery: each selected traveller unfolds first; its target appears only as the dock is drawn.
  const miniIn=NS.smooth(NS.window01(t,.85,1.45));m.layers.mini.style.opacity=String(miniIn);
  const specs=C.miniDocking;specs.forEach((s,i)=>{const mini=m.minis.get(s.travellerId),source=m.health.get(s.travellerId),a=1.0+i*.48,p=NS.outCubic(NS.window01(t,a,a+.62));mini.style.opacity=String(p);mini.style.transform=`scale(${NS.lerp(.18,1,p)})`;if(source)source.style.opacity=String(NS.lerp(1,.18,p));const edge=m.miniEdges.find(e=>e.travellerId===s.travellerId).path;edge.style.opacity=String(p);NS.drawProgress(edge,NS.smooth(NS.window01(t,a+.28,a+.92)));const target=m.commitments.get(s.target),cp=NS.outCubic(NS.window01(t,a+.62,a+1.05));target.style.opacity=String(Math.max(Number(target.style.opacity)||0,cp));target.style.transform=`translateY(${NS.lerp(18,0,cp)}px) scale(${NS.lerp(.94,1,cp)})`});
  C.dayLabels.forEach((s,i)=>{const e=m.dayLabels.get(s.id),p=NS.outCubic(NS.window01(t,1.75+i*1.0,2.35+i*1.0));e.style.opacity=String(p);e.style.transform=`translateX(${NS.lerp(-24,0,p)}px)`});
  // Secondary commitments and chronological rails appear only after the traveller-created anchors establish each day.
  C.commitments.forEach((s,i)=>{const e=m.commitments.get(s.id);const cur=Number(e.style.opacity)||0,p=NS.outCubic(NS.window01(t,2.15+(i%4)*.12+Math.floor(i/4)*.72,3.0+(i%4)*.12+Math.floor(i/4)*.72));e.style.opacity=String(Math.max(cur,p*.88))});m.programmeEdges.forEach((e,i)=>{const p=NS.smooth(NS.window01(t,2.75+i*.12,3.55+i*.12));e.style.opacity=String(p*.62);NS.drawProgress(e,p)});m.dockEdges.forEach((e,i)=>{const p=NS.smooth(NS.window01(t,3.35+i*.13,4.10+i*.13));e.path.style.opacity=String(p*.58);NS.drawProgress(e.path,p)});
  const idIn=NS.outCubic(NS.window01(t,4.55,5.25));connected.style.opacity=String(idIn);connected.style.transform=`translateY(${NS.lerp(10,0,idIn)}px)`;
  if(t<=.001){NS.setCamera(world,C.cameras.seq04Final.x,C.cameras.seq04Final.y,C.cameras.seq04Final.scale);scaleHud.style.opacity='1';summary.style.opacity='1';threshold.style.opacity='1';supplier.style.opacity='1';supplierEdges.forEach(e=>e.style.opacity='.82');nId.style.opacity='1';nId.textContent='NORTHSTAR · TRIP STATE';mode.style.opacity='1';connected.style.opacity='0';carryHealth.style.opacity='1';legacyNodes.forEach(e=>e.style.opacity='1');legacyEdges.forEach(e=>e.style.opacity='1');heroHeading.style.opacity='.28';m.layers.health.style.opacity='0';m.layers.mini.style.opacity='0';allProgramme.forEach(e=>e.style.opacity='0')}
 }
 NS.bootSequence({duration:D,renderAt});})();
