(()=>{const NS=window.NS,C=NS.OBJECTIVE_FIELD,D=9,world=document.getElementById('world'),svg=document.getElementById('world-svg'),m=NS.buildObjectiveField({world,svg,includeHeroes:true,includeConstraints:false}),M=C.mutation,hero=m.heroes.get(M.affectedHero);
 const rail=document.getElementById('maintain-rail'),wid=document.getElementById('world-id'),hud=document.getElementById('blast-hud');
 const signal=NS.inputCard(m.layers.hero,{id:'change-signal',source:M.signal.source,raw:M.signal.text,x:3910,y:1190,tone:M.signal.tone});signal.style.width='300px';signal.style.minHeight='105px';
 const trace=NS.svgPath(svg,'blast-trace','M4365 1572 L4705 1572 L5045 1572 L5385 1572 L5725 1572 C5900 1572 6100 1515 6350 1496','ns-edge is-ink'),dot=NS.svgCircle(svg,'blast-dot',12,'ns-trace');
 const watchEdge=m.dockEdges.find(e=>e.travellerId===M.outcomes.watch.travellerId)?.path;const target=m.commitments.get(M.commitment);
 const chips=[];[[M.outcomes.affected,5700,1360],[M.outcomes.watch,4880,1260],[M.outcomes.healthy,4880,1980]].forEach(([o,x,y])=>{const e=document.createElement('div');e.className='outcome-chip '+o.tone;e.textContent=`T${o.travellerId}  ${o.glyph} ${o.label}`;Object.assign(e.style,{left:x+'px',top:y+'px',opacity:'0'});m.layers.constraint.appendChild(e);chips.push(e)});
 function baseline(){m.layers.health.style.opacity='.58';m.layers.mini.style.opacity='1';[...m.dayLabels.values(),...m.commitments.values()].forEach(e=>e.style.opacity='1');m.programmeEdges.forEach(e=>e.style.opacity='.62');m.miniEdges.forEach(e=>e.path.style.opacity='1');m.dockEdges.forEach(e=>e.path.style.opacity='.58');m.heroes.forEach(h=>{h.root.style.opacity='.22';h.targetEdge.style.opacity='.22'});signal.style.opacity='0';trace.style.opacity='0';dot.style.opacity='0';hud.style.opacity='0'}
 function dimWorld(q){m.layers.health.style.opacity=String(NS.lerp(.58,.12,q));m.layers.mini.style.opacity=String(NS.lerp(1,.18,q));m.programmeEdges.forEach(e=>e.style.opacity=String(NS.lerp(.62,.10,q)));m.miniEdges.forEach(e=>e.path.style.opacity=String(NS.lerp(1,.14,q)));m.dockEdges.forEach(e=>e.path.style.opacity=String(NS.lerp(.58,.10,q)));[...m.commitments.entries()].forEach(([id,e])=>e.style.opacity=String(id===M.commitment?NS.lerp(1,.92,q):NS.lerp(1,.18,q)));[...m.dayLabels.values()].forEach(e=>e.style.opacity=String(NS.lerp(1,.20,q)))}
 function renderAt(t){t=NS.clamp(t,0,D);let p=NS.cubic(NS.window01(t,.65,2.25));NS.setCamera(world,NS.lerp(C.cameras.wideFinal.x,C.cameras.affected37.x,p),NS.lerp(C.cameras.wideFinal.y,C.cameras.affected37.y,p),NS.lerp(C.cameras.wideFinal.scale,C.cameras.affected37.scale,p));dimWorld(NS.smooth(NS.window01(t,.75,2.3)));hero.root.style.opacity=String(NS.lerp(.22,1,p));hero.root.style.transform=`scale(${NS.lerp(.72,1,p)})`;hero.targetEdge.style.opacity=String(NS.lerp(.22,.82,p));
  const sig=NS.outCubic(NS.window01(t,1.05,1.65));signal.style.opacity=String(sig);signal.style.transform=`translateY(${NS.lerp(14,0,sig)}px)`;
  // Reset hero baseline every frame, then apply settled selective consequences.
  ['flight','transfer1','hotel','transfer2','objective'].forEach(id=>NS.setHeroStage(hero,id,'green',hero.spec.stages.find(s=>s.id===id).meta));
  const ink=NS.smooth(NS.window01(t,1.45,2.0));if(ink>.05)NS.setHeroStage(hero,'flight','ink','TRACING CHANGE');
  const ft=NS.smooth(NS.window01(t,2.15,3.05));if(ft>.35){NS.setHeroStage(hero,'flight',M.stageStates.flight,M.stageMeta.flight);NS.setHeroStage(hero,'transfer1',M.stageStates.transfer1,M.stageMeta.transfer1)}
  const tr=NS.smooth(NS.window01(t,3.0,4.15));if(tr>.42){NS.setHeroStage(hero,'hotel',M.stageStates.hotel,M.stageMeta.hotel);NS.setHeroStage(hero,'transfer2',M.stageStates.transfer2,M.stageMeta.transfer2)}
  const obj=NS.smooth(NS.window01(t,4.0,5.0));if(obj>.35){NS.setHeroStage(hero,'objective',M.stageStates.objective,M.stageMeta.objective);NS.setTone(target,'brass');target.querySelector('.time').textContent=M.commitmentWatch}else{NS.setTone(target,'green');target.querySelector('.time').textContent=M.commitmentBase}
  trace.style.opacity=String(NS.smooth(NS.window01(t,1.65,2.05)));const prog=NS.smooth(NS.window01(t,1.75,5.15));NS.drawProgress(trace,prog);if(prog>0&&prog<1){const pt=NS.pointOnPath(trace,prog);dot.setAttribute('cx',pt.x);dot.setAttribute('cy',pt.y);dot.style.opacity=String(NS.bell(prog))}else dot.style.opacity='0';
  const watch=NS.smooth(NS.window01(t,5.0,6.25));if(watchEdge){watchEdge.style.opacity=String(NS.lerp(.10,.92,watch));watchEdge.setAttribute('class','ns-edge is-brass')}const wm=m.health.get(M.outcomes.watch.travellerId);if(wm&&watch>.35)NS.setHealth(wm,'brass','▲');const hm=m.health.get(M.outcomes.healthy.travellerId);if(hm)NS.setHealth(hm,'green','✓');
  chips.forEach((e,i)=>{const q=NS.outCubic(NS.window01(t,5.5+i*.38,6.15+i*.38));e.style.opacity=String(q);e.style.transform=`translateY(${NS.lerp(10,0,q)}px)`});const hi=NS.outCubic(NS.window01(t,6.65,7.35));hud.style.opacity=String(hi);
  if(t<=.001){NS.setCamera(world,C.cameras.wideFinal.x,C.cameras.wideFinal.y,C.cameras.wideFinal.scale);baseline();NS.setTone(target,'green');const wm=m.health.get(M.outcomes.watch.travellerId);if(wm)NS.setHealth(wm,'green','✓');chips.forEach(e=>e.style.opacity='0')}
 }
 baseline();NS.bootSequence({duration:D,renderAt});})();
