/**
 * Frozen Nuitée capture query literals (RV-N7, WP-R4-REDO).
 *
 * GENERATED by scripts/build-northstar-hotel-fixtures.ts — do not edit.
 * These are the exact query objects that produced the committed recordings
 * under fixtures/recordings/nuitee; recording ids hash them, so REPLAY
 * resolves only when the objects match byte-for-byte. Provider identifiers
 * below are genuine sandbox values captured at generation time.
 */
import type {
  HotelActionQuery,
  HotelBookQuery,
  HotelQuoteQuery,
  HotelRetrieveQuery,
  HotelSearchQuery,
  StayContextQuery,
} from '../../src/contracts/capabilities.ts';

export const NUITEE_CAPTURE_SEARCH_QUERY: HotelSearchQuery = {
  "location": {
    "coordinates": {
      "latitude": 1.2839,
      "longitude": 103.8607,
      "radiusKm": 5
    }
  },
  "checkInDate": "2026-10-01",
  "checkOutDate": "2026-10-04",
  "guests": {
    "adults": 1
  },
  "rooms": 1
};

export const NUITEE_CAPTURE_QUOTE_QUERY: HotelQuoteQuery = {
  "rateId": "3gAWonJzkd4AEaRzcmlk2gEHR1kyRE1OSldNTTNUS05aWUdZMlRFTUJYR0EzR0dOWlZHNFpYWU1KREdJWURFTlJSR0FZREM3QlNHQVpETU1KUUdBMkhZWkxPTDVLVkc3Q1ZLTjZGS1UyRVBRWVVDTUNEUFEyREtNUlpQUlVWQVoyVkpCNkRDTlpZRzQyRFFPSlpHRVlEQ05CVEpGWEhLMlpER0VaVFFOUlZHVVJUQ01SVUc0V1RDTVpZR1kyVEs3Q1NJWkhIWU1SUUdJM0RBT0pTSEFZREtNQlFQUVlYWVVSUkdFMlRBN0JWR1k0VElNQkRLSkhTR1VTR0pZUlRFTUJTR1lXVEFPSk5HSTRDQU1CVkhJWURBSVmjcHJjy0CByzMzMzMzpW9yX3ByywAAAAAAAAAApW9yX2NtywAAAAAAAAAAomNtywAAAAAAAAAAo3BjZLMyMDI2LTA5LTI4IDA1OjAwOjAwonJ0o1JGTqNicmSiUk-kbXJpZMCjbXJuwKNoZHDAo2ZybqCjc3Juq0RFTFVYRSBQTFVTo29jbgGkcHJrc8CjZGV0ywAAAAAAAAAAomNwgqFwkYWhdLMyMDI2LTA5LTI4IDA1OjAwOjAwoWHLQGe5mZmZmZqhY6NVU0SidHmmYW1vdW50onR6o0dNVKJydKNSRk6kc2hpZKYxMzg2NTWjc2lkAqNoaWSnbHAyMWQ5ZqNvY2ORgaFhAaNjdXKjVVNEomduolVTomNpqjIwMjYtMTAtMDGiY2-qMjAyNi0xMC0wNKNnaWSgomNyywAAAAAAAAAApHNzaWTZMHNlc3Npb25fMDFhMDJlYjM3ZDZkeDBrZWdzakJ2QzhRNWt2VDZKSDY0WWJSOGZVWaNpc2jCo3NzcKCjaWZtwqVpZmNocsKjaWZywqVzZWFpZKCibmuxbGl0ZWFwaW9uYm9hcmRpbmeidHiShKFpw6Fkt1Byb3BlcnR5IHNlcnZpY2UgY2hhcmdloWHLQEx4UeuFHrihY6NVU0SEoWnCoWSjVEFYoWHLQEmgAAAAAAChY6NVU0SibHDAo2JrdAA="
};

export const NUITEE_CAPTURE_BOOK_QUERY: HotelBookQuery = {
  "quoteId": "aVFthZabE",
  "guestNames": [
    "Northstar Replay"
  ],
  "clientReference": "qoder-atlas-rv-n7"
};

export const NUITEE_CAPTURE_RETRIEVE_QUERY: HotelRetrieveQuery = {
  "bookingId": "940nnns93"
};

export const NUITEE_CAPTURE_STAY_CONTEXT_QUERY: StayContextQuery = {
  "stayElementId": "940nnns93"
};

export const NUITEE_CAPTURE_CANCEL_QUERY: HotelActionQuery = {
  "stayElementId": "940nnns93",
  "reason": "capture-completion"
};
